all: compile run clean

compile:
	@echo "-------------------------------"
	@echo "Compiling...."
	@gcc main.c -o test -lm
	
run:
	@echo "-----------------"
	./test
	
clean:
	@echo "--------------------------"
	@echo "Removing compiled files..."
	@rm -f test

	


